android.useAndroidX=true
kotlin.code.style=official
# -Duser.language=en : bug MsDosDateTimeUtils packDate VerifyException (locale th = calendar buddhist -> year 2569 > max DOS 2107)
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US
android.nonTransitiveRClass=true
android.enableJetifier=false
